const products = [
  { productName: "Wireless Mouse", price: 25.99, rating: 4.5 },
  { productName: "Bluetooth Keyboard", price: 45.0, rating: 4.3 },
  { productName: "Gaming Headset", price: 79.99, rating: 4.6 },
  { productName: "USB-C Charger", price: 19.99, rating: 4.4 },
  { productName: "Laptop Stand", price: 34.5, rating: 4.2 },
  { productName: "Smartphone Case", price: 14.99, rating: 4.1 },
  { productName: "Portable SSD", price: 129.99, rating: 4.8 },
  { productName: "Webcam HD", price: 59.99, rating: 4.3 },
  { productName: "Mechanical Keyboard", price: 99.99, rating: 4.7 },
  { productName: "Noise Cancelling Headphones", price: 199.99, rating: 4.9 },
  { productName: "Smartwatch", price: 149.99, rating: 4.4 },
  { productName: "Tablet Stand", price: 22.99, rating: 4.2 },
  { productName: "External Hard Drive", price: 89.99, rating: 4.6 },
  { productName: "Wireless Charger", price: 29.99, rating: 4.3 },
  { productName: "LED Desk Lamp", price: 39.99, rating: 4.5 },
  { productName: "Fitness Tracker", price: 69.99, rating: 4.1 },
  { productName: "Action Camera", price: 249.99, rating: 4.7 },
  { productName: "Bluetooth Speaker", price: 55.99, rating: 4.4 },
  { productName: "Graphics Tablet", price: 89.5, rating: 4.6 },
  { productName: "Wireless Earbuds", price: 79.99, rating: 4.3 },
  { productName: "Smart Home Hub", price: 129.0, rating: 4.5 },
  { productName: "VR Headset", price: 299.99, rating: 4.8 },
  { productName: "Portable Monitor", price: 179.99, rating: 4.6 },
  { productName: "Ergonomic Chair", price: 349.99, rating: 4.7 },
  { productName: "Desk Organizer", price: 18.75, rating: 4.0 },
  { productName: "Power Bank", price: 27.99, rating: 4.4 },
  { productName: "WiFi Router", price: 119.99, rating: 4.5 },
  { productName: "Smart Light Bulb", price: 24.99, rating: 4.2 },
  { productName: "Monitor Arm", price: 64.99, rating: 4.6 },
  { productName: "USB Hub", price: 21.99, rating: 4.3 },
];
